# Generated by Django 5.2.3 on 2025-07-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_patient',
            new_name='is_admin',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_nurse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_pharmacist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'nurse'), ('pharmacist', 'pharmacist'), ('admin', 'Admin'), ('user', 'user')], max_length=10),
        ),
    ]
