# Generated by Django 5.2.3 on 2025-07-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_is_patient_profile_is_admin_profile_is_nurse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_nurse',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_pharmacist',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('admin', 'Admin'), ('user', 'User')], max_length=20),
        ),
    ]
