# Generated by Django 5.2.3 on 2025-07-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_is_admin_remove_profile_is_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
