# Generated by Django 5.2.3 on 2025-07-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('admin', 'Admin'), ('user', 'User'), ('patient', 'Patient')], max_length=20),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
