# Generated by Django 5.2.3 on 2025-07-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_role_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('admin', 'Admin'), ('user', 'User'), ('patient', 'Patient')], max_length=20),
        ),
    ]
