# Generated by Django 5.2.3 on 2025-07-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_consultation_consultationpatient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='profile_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(default='Unknown', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
