# Generated by Django 5.2.3 on 2025-08-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('admin', 'Admin'), ('patient', 'Patient')], max_length=20),
        ),
    ]
