# Generated by Django 5.2.3 on 2025-07-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
