# Generated by Django 5.2.3 on 2025-07-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_profile_image_patient_image_patient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact',
            field=models.CharField(default=123456789, max_length=20),
            preserve_default=False,
        ),
    ]
