# Generated by Django 5.2.3 on 2025-07-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contact',
        ),
    ]
