# Generated by Django 5.2.3 on 2025-07-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_patient_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
