# Generated by Django 5.2.3 on 2025-07-30 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_appointment_patient'),
        ('patients', '0009_patient_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='age',
        ),
        migrations.AlterField(
            model_name='consultationpatient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
