# Generated by Django 5.2.3 on 2025-08-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_remove_consultation_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationpatient',
            name='medicine_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
