# Generated by Django 5.2.3 on 2025-07-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctor_fees_doctor_image_alter_doctor_doctor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_id',
        ),
    ]
